// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOeBke-vRnSxsinIlW1I9U_lMkqPBaEhU',
    appId: '1:868555733738:web:cba80874c22d0b0df9b593',
    messagingSenderId: '868555733738',
    projectId: 'store-app-a0f1d',
    authDomain: 'store-app-a0f1d.firebaseapp.com',
    storageBucket: 'store-app-a0f1d.appspot.com',
    measurementId: 'G-53MW2D8P93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBzRHmWIsZgUa8GDLxpe_ETEfVg86o19U',
    appId: '1:868555733738:android:004d9ac5b59b6f56f9b593',
    messagingSenderId: '868555733738',
    projectId: 'store-app-a0f1d',
    storageBucket: 'store-app-a0f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvYzV-Sq7GbCMqcb6iwV577ayNVeG6U1A',
    appId: '1:868555733738:ios:ba00361a6f535b74f9b593',
    messagingSenderId: '868555733738',
    projectId: 'store-app-a0f1d',
    storageBucket: 'store-app-a0f1d.appspot.com',
    iosClientId: '868555733738-3omqj9ub07djp5ushvop5tp6b33f4mqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvYzV-Sq7GbCMqcb6iwV577ayNVeG6U1A',
    appId: '1:868555733738:ios:ba00361a6f535b74f9b593',
    messagingSenderId: '868555733738',
    projectId: 'store-app-a0f1d',
    storageBucket: 'store-app-a0f1d.appspot.com',
    iosClientId: '868555733738-3omqj9ub07djp5ushvop5tp6b33f4mqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );
}
